on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/setup-buildx-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ adrianhdzm13/udemy-devops:0.0.1 }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
